# Generated by Django 4.2.2 on 2023-06-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(db_comment="Product name", max_length=255),
        ),
    ]
