# Generated by Django 4.2.2 on 2023-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="media/images/products", verbose_name="Product image"
            ),
        ),
    ]
