version: "3.9"
services:
  postgres:
    image: postgres:16.2-alpine3.19  
    container_name: shopify-db

    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
      
  redis:
    image: redis:7.0-alpine3.18
    container_name: shopify-redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: shopify-smtp
    ports:
      - 5000:5001
      - 2525:2525
    restart: always

  web:
    container_name: shopify-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh
    ports:
      - 8000:8002
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - .:/app

  celery:
    container_name: shopify-celery
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app

  celery-beat:
    container_name: shopify-celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A storefront beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    container_name: shopify-flower
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A storefront flower
    depends_on:
      - web
      - redis
      - celery
    environment:
      DEBUG: 1
      CELERY_BROKER: redis://shopify-redis:6379/0
      CELERY_BACKEND: redis://shopify-redis:6379/0
    ports:
      - 5555:5555

  tests:
    container_name: shopify-tests
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-it.sh postgres:5432
    depends_on:
      - redis
      - postgres
    tty: true
    volumes:
      - .:/app

volumes:
  mysqldata:
  redisdata:
